export type AttendanceManagerDto = {
  id?: number | string;
  idx?: number | string;
  year?: number | string;
  month?: number | string;
  week?: number | string;
  attend_card_no?: number | string;
  attendCardNo?: number | string;
  emp_no?: number | string;
  empNo?: number | string;
  emo_no?: number | string;
  emp_name?: string;
  empName?: string;
  dept_code?: string;
  deptCode?: string;
  dept_name?: string;
  deptName?: string;
  rank_code?: string;
  rankCode?: string;
  rank_name?: string;
  rankName?: string;
  position?: string;
  attend_date?: string;
  attendDate?: string;
  attend_record_date?: string;
  attendRecordDate?: string;
  work_date?: string;
  workDate?: string;
  check_in?: string;
  checkIn?: string;
  attendance_time?: string;
  attendanceTime?: string;
  check_out?: string;
  checkOut?: string;
  leave_working_time?: string;
  leaveWorkingTime?: string;
  total_working?: string;
  totalWorking?: string;
  attend_status?: string;
  attendStatus?: string;
  attend_status_name?: string;
  attendStatusName?: string;
  attend_code?: string;
  attendCode?: string;
  attendance_code?: string;
  attendanceCode?: string;
  ttendance_code?: string;
  ttendanceCode?: string;
  attend_code_name?: string;
  attendCodeName?: string;
  attendance_name?: string;
  attendanceName?: string;
  detail_code?: string;
  detailCode?: string;
  attend_codes?: string[];
  attendCodes?: string[];
  attendance_codes?: string[];
  attendanceCodes?: string[];
  attend_reason?: string;
  attendReason?: string;
  etc?: string;
  memo?: string;
  remark?: string;
};

export type AttendanceManagerListResponseDto = {
  attendinfo?: AttendanceManagerDto[];
  attendInfo?: AttendanceManagerDto[];
  employeelist?: AttendanceManagerDto[];
  attendanceList?: AttendanceManagerDto[];
  attendancelist?: AttendanceManagerDto[];
  attendweeklist?: AttendanceManagerDto[];
  attendWeekList?: AttendanceManagerDto[];
  attendmonthlist?: AttendanceManagerDto[];
  attendMonthList?: AttendanceManagerDto[];
  attendyearlist?: AttendanceManagerDto[];
  attendYearList?: AttendanceManagerDto[];
  attendManagerList?: AttendanceManagerDto[];
  attendmanagerlist?: AttendanceManagerDto[];
  items?: AttendanceManagerDto[];
  rows?: AttendanceManagerDto[];
  list?: AttendanceManagerDto[];
  data?: AttendanceManagerDto[];
  totalCount?: number | string;
  total_count?: number | string;
  deviceTimeCount?: number | string;
  device_time_count?: number | string;
  status?: string;
  message?: string;
};

export type AttendanceUploadFailedRowDto = {
  row?: number | string;
  row_no?: number | string;
  rowNo?: number | string;
  emp_no?: number | string;
  empNo?: number | string;
  emp_name?: string;
  empName?: string;
  reason?: string;
  message?: string;
};

export type AttendanceUploadResultDto = {
  attendinfo?: AttendanceUploadResultDto | AttendanceUploadResultDto[];
  attendInfo?: AttendanceUploadResultDto | AttendanceUploadResultDto[];
  upload_id?: number | string;
  uploadId?: number | string;
  total_count?: number | string;
  totalCount?: number | string;
  success_count?: number | string;
  successCount?: number | string;
  overwrite_count?: number | string;
  overwriteCount?: number | string;
  failed_count?: number | string;
  failedCount?: number | string;
  failed_rows?: AttendanceUploadFailedRowDto[];
  failedRows?: AttendanceUploadFailedRowDto[];
  errors?: string[];
  message?: string;
  status?: string;
  data?: AttendanceUploadResultDto;
  result?: AttendanceUploadResultDto;
  upload_result?: AttendanceUploadResultDto;
  uploadResult?: AttendanceUploadResultDto;
};

export type AttendanceUploadStatusDto = {
  uploaded?: boolean | string;
  is_uploaded?: boolean | string;
  isUploaded?: boolean | string;
  exists?: boolean | string;
  upload_id?: number | string;
  uploadId?: number | string;
  total_count?: number | string;
  totalCount?: number | string;
  success_count?: number | string;
  successCount?: number | string;
  uploaded_at?: string;
  uploadedAt?: string;
  file_name?: string;
  fileName?: string;
  message?: string;
  status?: string;
};

