export type AttendanceManagerDto = {
  id?: number | string;
  idx?: number | string;
  emp_no?: number | string;
  empNo?: number | string;
  emo_no?: number | string;
  attend_card_no?: number | string;
  attendCardNo?: number | string;
  emp_name?: string;
  empName?: string;
  dept_name?: string;
  deptName?: string;
  position?: string;
  attend_date?: string;
  attendDate?: string;
  attend_record_date?: string;
  attendRecordDate?: string;
  work_date?: string;
  workDate?: string;
  check_in?: string;
  checkIn?: string;
  attendance_time?: string;
  attendanceTime?: string;
  check_out?: string;
  checkOut?: string;
  leave_working_time?: string;
  leaveWorkingTime?: string;
  total_working?: string;
  totalWorking?: string;
  attend_code?: string;
  attendCode?: string;
  detail_code?: string;
  detailCode?: string;
  attend_reason?: string;
  attendReason?: string;
  etc?: string;
  memo?: string;
  remark?: string;
};

export type AttendanceManagerListResponseDto = {
  employeelist?: AttendanceManagerDto[];
  attendanceList?: AttendanceManagerDto[];
  attendancelist?: AttendanceManagerDto[];
  attendweeklist?: AttendanceManagerDto[];
  attendWeekList?: AttendanceManagerDto[];
  attendmonthlist?: AttendanceManagerDto[];
  attendMonthList?: AttendanceManagerDto[];
  attendyearlist?: AttendanceManagerDto[];
  attendYearList?: AttendanceManagerDto[];
  attendManagerList?: AttendanceManagerDto[];
  attendmanagerlist?: AttendanceManagerDto[];
  data?: AttendanceManagerDto[];
  status?: string;
  message?: string;
};
